# Generated by Django 4.2.4 on 2023-10-07 00:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Nome')),
                ('ean', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='O Ean deve conter 13 caracteres', regex='^.{13}$')], verbose_name='EAN')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produtos', verbose_name='Imagem')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Preço mínimo')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Preço máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='PriceVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='PromoterApp.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação de preço',
                'verbose_name_plural': 'Variações de preço',
            },
        ),
    ]
