# Generated by Django 4.2.4 on 2023-10-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PromoterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricevariation',
            options={'verbose_name': 'Variação de preço', 'verbose_name_plural': 'Variações de preço'},
        ),
        migrations.AlterField(
            model_name='pricevariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='PromoterApp.product', verbose_name='Produto'),
        ),
    ]
